#!/bin/bash
set -e

export PYTHONUNBUFFERED=1

# Set TridaPad host from Render's environment variable
export TRIDAPAD_HOST="$RENDER_EXTERNAL_HOSTNAME"

# Execute the main docker-entrypoint script with passed arguments
exec /app/bin/docker-entrypoint "$@"
